TOKEN = '7688192538:AAFmbZJlWaaaHqvCeCkUACNpUxcep6ppCb8'
ADMIN_CHAT_ID = '8047942590'  # Replace with your Telegram chat ID for notifications

# Payment Gateway Configuration
API_KEY = '46460da2747c4f639d3f3681a42edec8'
MCH_ID = '100789053'
PAYMENT_URL = 'https://api.watchglbpay.com/pay/web'
CALLBACK_URL = 'https://yourdomain.com/callback'
REDIRECT_URL = 'https://yourdomain.com/success'